version: "3"

services:

  example:
    image: nginx:alpine
    container_name: example
    ports:
      - "80:80"
    volumes:
      - ./:/app
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - sssr-network

  sssr:
    build:
      context: ../
      dockerfile: Dockerfile
    restart: always
    container_name: sssr
    user: "1000:1000"
    environment:
      - "WORKERS=1"
      - "DEBUG=sssr*"
    ports:
      - "3000:3000"
    networks:
      - sssr-network

networks:
  sssr-network:
